name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: |
        pip install uv
    
    - name: Build project with dev dependencies
      run: |
        uv sync --group dev
    
    - name: Run type checking
      run: |
        uvx ty check
    
    - name: Run linting
      run: |
        uvx ruff check
    
    - name: Run tests
      run: |
        uv run pytest 